# This workflow will create a new release tag

name: Release Tag
    
on:
  workflow_call:
    inputs:
      version:
        description: 'Release version. Format: <major>.<minor>.<patch>(.tag)'
        type: string
        required: true
      target:
        description: 'Path to target platform'
        type: string
        required: true
      pom:
        description: 'Path to pom.xml. Defaults to pom.xml in working directory'
        type: string
        required: false
        default: 'pom.xml'

jobs:        
  release-tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Fail if branch is main
      if: github.ref == 'refs/heads/main'
      run: |
        echo "This workflow should not be triggered on main"
        exit 1
        
    - name: Validate version format
      run: echo '${{ inputs.version }}' | grep -P '^\d+\.\d+\.\d+(\.[a-z0-9]+)?$'

    - uses: actions/checkout@v3

    - name: Bump versions
      uses: eclipse-set/build/.github/actions/set-version@main
      with:
        version: ${{ inputs.version }}
        target: ${{ inputs.target }}
        pom: ${{ inputs.pom }}

    - name: Update DEPENDENCIES
      uses: eclipse-set/build/.github/actions/update-dependency-file@main
      with:
        pom: ${{ inputs.pom }}        

    - name: Push to Github
      run: |
        git config user.name 'eclipse-set-bot'
        git config user.email 'set-bot@eclipse.org'
        git status
        git add -A
        git commit --allow-empty -m "Release ${{ inputs.version }}" 
        git status
        git tag -d v${{ inputs.version }} || true
        git tag v${{ inputs.version }}
        git status
        git push -f -u origin v${{ inputs.version }}
        git status
