name: Update DEPENDENCIES file
    
on:
  workflow_call:
    inputs:
      pom:
        description: 'Path to pom.xml'
        type: string
        required: false
        default: 'pom.xml'

jobs:        
  update-DEPENDENCIES:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_BOT_TOKEN }}

    - name: Update DEPENDENCIES
      uses: eclipse-set/build/.github/actions/update-dependency-file@main
      with:
        pom: ${{ inputs.pom }}
     
    - name: Push to Github
      run: |
        git config user.name 'eclipse-set-bot'
        git config user.email 'set-bot@eclipse.org'
        git status
        git add DEPENDENCIES || true
        git commit -m "Update DEPENDENCIES" || true
        git push || true
